# Generated by Django 3.2.5 on 2021-11-28 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='readText',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='snsImage',
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='board_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='good',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='read',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
