# Generated by Django 3.2.5 on 2021-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0002_auto_20211128_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='board_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
