# Generated by Django 3.2.5 on 2021-12-04 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0003_alter_boardmodel_board_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('comment_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snsApp.boardmodel')),
            ],
        ),
    ]
